spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/maria
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    pool:
      max-connections: 10
server:
  port: 8444